### ISSUE TITLE
TypeError: __call__() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by Veidit** [Julian/mkenv#22] opened 2017-10-18 12:44 UTC
Getting this error after installing mkenv with pip:
`john@desktop-bo2ejhd ~ $ mkenv
Traceback (most recent call last):
  File "/usr/local/bin/mkenv", line 7, in <module>
    from mkenv.make import main
  File "/Library/Python/2.7/site-packages/mkenv/make.py", line 14, in <module>
    from packaging.requirements import Requirement
  File "/Library/Python/2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)`

Installation looked good:
`john@desktop-bo2ejhd ~ $ sudo pip install mkenv
The directory '/Users/john/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/john/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mkenv
  Downloading mkenv-3.0.0-py2-none-any.whl
Requirement already satisfied: packaging in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: appdirs in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: click in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: attrs in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: virtualenv in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: filesystems in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: pytoml in /Library/Python/2.7/site-packages (from mkenv)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from packaging->mkenv)
Requirement already satisfied: pyparsing in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from packaging->mkenv)
Requirement already satisfied: pyrsistent in /Library/Python/2.7/site-packages (from filesystems->mkenv)
Installing collected packages: mkenv
Successfully installed mkenv-3.0.0`

Version of python:
`john@desktop-bo2ejhd ~ $ python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.`

Running this on OSX 10.12.6 that is up to date.

**Comment by Julian** [comment] 2017-10-18 12:56
Hey!

That looks possibly like a wrong version of `packaging` maybe.

Can I see the output of `pip list`?

Also please never run pip with sudo :)! That is the whole purpose (or one of them) of virtualenvs -- even if you want to install mkenv itself I'd recommend doing so into a virtualenv (eventually mkenv should do that itself I think, which is issue #6).

**Comment by Veidit** [comment] 2017-10-18 13:01
`altgraph (0.10.2)
appdirs (1.4.3)
attrs (17.2.0)
autoenv (1.0.0)
bdist-mpkg (0.5.0)
bonjour-py (0.3)
click (6.7)
filesystems (0.14.0)
macholib (1.5.1)
matplotlib (1.3.1)
mkenv (3.0.0)
modulegraph (0.10.4)
numpy (1.8.0rc1)
packaging (16.8)
pip (9.0.1)
protobuf (3.4.1)
py2app (0.7.3)
pyobjc-core (2.5.1)
pyobjc-framework-Accounts (2.5.1)
pyobjc-framework-AddressBook (2.5.1)
pyobjc-framework-AppleScriptKit (2.5.1)
pyobjc-framework-AppleScriptObjC (2.5.1)
pyobjc-framework-Automator (2.5.1)
pyobjc-framework-CFNetwork (2.5.1)
pyobjc-framework-Cocoa (2.5.1)
pyobjc-framework-Collaboration (2.5.1)
pyobjc-framework-CoreData (2.5.1)
pyobjc-framework-CoreLocation (2.5.1)
pyobjc-framework-CoreText (2.5.1)
pyobjc-framework-DictionaryServices (2.5.1)
pyobjc-framework-EventKit (2.5.1)
pyobjc-framework-ExceptionHandling (2.5.1)
pyobjc-framework-FSEvents (2.5.1)
pyobjc-framework-InputMethodKit (2.5.1)
pyobjc-framework-InstallerPlugins (2.5.1)
pyobjc-framework-InstantMessage (2.5.1)
pyobjc-framework-LatentSemanticMapping (2.5.1)
pyobjc-framework-LaunchServices (2.5.1)
pyobjc-framework-Message (2.5.1)
pyobjc-framework-OpenDirectory (2.5.1)
pyobjc-framework-PreferencePanes (2.5.1)
pyobjc-framework-PubSub (2.5.1)
pyobjc-framework-QTKit (2.5.1)
pyobjc-framework-Quartz (2.5.1)
pyobjc-framework-ScreenSaver (2.5.1)
pyobjc-framework-ScriptingBridge (2.5.1)
pyobjc-framework-SearchKit (2.5.1)
pyobjc-framework-ServiceManagement (2.5.1)
pyobjc-framework-Social (2.5.1)
pyobjc-framework-SyncServices (2.5.1)
pyobjc-framework-SystemConfiguration (2.5.1)
pyobjc-framework-WebKit (2.5.1)
pyOpenSSL (0.13.1)
pyparsing (2.0.1)
pyrsistent (0.14.0)
python-dateutil (1.5)
pytoml (0.1.14)
pytz (2013.7)
scipy (0.13.0b1)
setuptools (18.5)
six (1.4.1)
virtualenv (15.1.0)
xattr (0.6.4)
yasm (0.0)
zope.interface (4.1.1)`


Hmm I would love to install mkenv in a virtualenv that is in my path easily, got an good guide for that?

**Comment by Veidit** [comment] 2017-10-25 13:23
How did it go?

**Comment by Julian** [comment] 2017-10-26 16:23
@Veidit so, embarassingly, until #6 is done, the way I currently would recommend installing into a venv that's still on your path looks like:

```
virtualenv ~/.local/share/virtualenvs/mkenv && ~/.local/share/virtualenvs/mkenv/bin/pip install -U mkenv && for f in ~/.local/share/virtualenvs/mkenv/bin/*env*; do ln -s $f ~/.local/bin/; done
```

Would really love a hand on #6 though certainly.

**Comment by Julian** [comment] 2017-10-26 16:57
Oh and, for your original issue, I'm hearing that the cause might be due to the version of pyparsing you've got -- try upgrading pyparsing to 2.2.0 and see if that fixes it? Lemme know if it does, would be happy to pin the version there to make sure you get a working one.

**Comment by Julian** [comment] 2017-10-29 13:03
@Veidit any luck?

**Comment by Veidit** [comment] 2017-10-30 08:45
No luck so far. Trying to upgrade pyparsing with pip just gives me rights errors even if I am using sudo. Sorry for the late reply.

**Comment by Julian** [comment] 2017-11-18 23:35
I think the above should help -- if you need a hand with your permissions stuff lemme know, for now gonna close this but yeah lemme know if this still doesn't work!

**Closed by Julian** 2017-11-18 23:35 UTC
